//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankParsianReversal
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientReversalRequestData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService")]
    public partial class ClientReversalRequestData : object
    {
        
        private string LoginAccountField;
        
        private long TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LoginAccount
        {
            get
            {
                return this.LoginAccountField;
            }
            set
            {
                this.LoginAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDataViewModelBase", Namespace="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BankParsianReversal.ClientReversalResponseData))]
    public partial class ResponseDataViewModelBase : object
    {
        
        private short StatusField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientReversalResponseData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService")]
    public partial class ClientReversalResponseData : BankParsianReversal.ResponseDataViewModelBase
    {
        
        private long TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService", ConfigurationName="BankParsianReversal.ReversalServiceSoap")]
    public interface ReversalServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService/ReversalRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<BankParsianReversal.ReversalRequestResponse> ReversalRequestAsync(BankParsianReversal.ReversalRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReversalRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReversalRequest", Namespace="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService", Order=0)]
        public BankParsianReversal.ReversalRequestRequestBody Body;
        
        public ReversalRequestRequest()
        {
        }
        
        public ReversalRequestRequest(BankParsianReversal.ReversalRequestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService")]
    public partial class ReversalRequestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankParsianReversal.ClientReversalRequestData requestData;
        
        public ReversalRequestRequestBody()
        {
        }
        
        public ReversalRequestRequestBody(BankParsianReversal.ClientReversalRequestData requestData)
        {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReversalRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReversalRequestResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService", Order=0)]
        public BankParsianReversal.ReversalRequestResponseBody Body;
        
        public ReversalRequestResponse()
        {
        }
        
        public ReversalRequestResponse(BankParsianReversal.ReversalRequestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Reversal/ReversalService")]
    public partial class ReversalRequestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BankParsianReversal.ClientReversalResponseData ReversalRequestResult;
        
        public ReversalRequestResponseBody()
        {
        }
        
        public ReversalRequestResponseBody(BankParsianReversal.ClientReversalResponseData ReversalRequestResult)
        {
            this.ReversalRequestResult = ReversalRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ReversalServiceSoapChannel : BankParsianReversal.ReversalServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ReversalServiceSoapClient : System.ServiceModel.ClientBase<BankParsianReversal.ReversalServiceSoap>, BankParsianReversal.ReversalServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReversalServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ReversalServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ReversalServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReversalServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReversalServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReversalServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReversalServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReversalServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BankParsianReversal.ReversalRequestResponse> BankParsianReversal.ReversalServiceSoap.ReversalRequestAsync(BankParsianReversal.ReversalRequestRequest request)
        {
            return base.Channel.ReversalRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<BankParsianReversal.ReversalRequestResponse> ReversalRequestAsync(BankParsianReversal.ClientReversalRequestData requestData)
        {
            BankParsianReversal.ReversalRequestRequest inValue = new BankParsianReversal.ReversalRequestRequest();
            inValue.Body = new BankParsianReversal.ReversalRequestRequestBody();
            inValue.Body.requestData = requestData;
            return ((BankParsianReversal.ReversalServiceSoap)(this)).ReversalRequestAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ReversalServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ReversalServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ReversalServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://pec.shaparak.ir/NewIPGServices/Reverse/ReversalService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ReversalServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://pec.shaparak.ir/NewIPGServices/Reverse/ReversalService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ReversalServiceSoap,
            
            ReversalServiceSoap12,
        }
    }
}
